(module
  (import "c4wa" "printf" (func $printf (param i32) (param i32)))
  (global $@stack (mut i32) (i32.const 1))
  (memory (export "memory") 1)
  (data (i32.const 1024) "foo(%d)\0A\00bar(%d)\0A\00")
  (func $foo (param $level i32)
    (local $@stack_entry i32)
    (set_local $@stack_entry (global.get $@stack))
    (i64.store align=1 (global.get $@stack) (i64.extend_i32_s (get_local $level)))
    (call $printf (i32.const 1024) (global.get $@stack))
    (if (i32.gt_s (get_local $level) (i32.const 0))
      (then
        (call $bar (i32.sub (get_local $level) (i32.const 1)))))
    (global.set $@stack (get_local $@stack_entry)))
  (func $main (export "main") (result i32)
    (call $foo (i32.const 10))
    (i32.const 0))
  (func $bar (param $level i32)
    (local $@stack_entry i32)
    (set_local $@stack_entry (global.get $@stack))
    (i64.store align=1 (global.get $@stack) (i64.extend_i32_s (get_local $level)))
    (call $printf (i32.const 1033) (global.get $@stack))
    (if (i32.gt_s (get_local $level) (i32.const 0))
      (then
        (call $foo (i32.sub (get_local $level) (i32.const 1)))))
    (global.set $@stack (get_local $@stack_entry))))
