(module
  (import "c4wa" "printf" (func $printf (param i32) (param i32)))
  (global $@stack (mut i32) (i32.const 0))
  (memory (export "memory") 1)
  (data (i32.const 1024) "29^3 + 11^3 = %d\5Cn\00")
  (func $main (export "main") (result i32)
    (local $@stack_entry i32)
    (local $a i32)
    (local $b i32)
    (local $c i32)
    (set_local $@stack_entry (global.get $@stack))
    (set_local $a (i32.const 29))
    (set_local $b (i32.const 11))
    (set_local $c (i32.add (i32.mul (i32.mul (get_local $a) (get_local $a)) (get_local $a)) (i32.mul (i32.mul (get_local $b) (get_local $b)) (get_local $b))))
    (i64.store (global.get $@stack) (i64.const 1024))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (i64.store (global.get $@stack) (i64.extend_i32_s (get_local $c)))
    (global.set $@stack (i32.sub (global.get $@stack) (i32.const 8)))
    (call $printf (global.get $@stack) (i32.const 2))
    (global.set $@stack (get_local $@stack_entry))
    (return (i32.const 0))))
