(module
  (import "c4wa" "printf" (func $printf (param i32) (param i32)))
  (global $__last_offset (mut i32) (i32.const 1100))
  (global $__available_size (mut i32) (i32.const -1))
  (global $precision f64 (f64.const 1.0E-9))
  (global $@stack (mut i32) (i32.const 0))
  (memory (export "memory") 1)
  (data (i32.const 1024) "a = %d, b = %d, c = %d: \00no roots\0A\00one root %.6f\0A\00two roots, %.6f and %.6f\0A\00")
  (func $solve_square_equation (param $a f64) (param $b f64) (param $c f64) (param $roots i32) (param $p_status i32)
    (local $d f64)
    (local $sqrt_d f64)
    (set_local $d (f64.sub (f64.mul (get_local $b) (get_local $b)) (f64.mul (f64.mul (f64.const 4.0) (get_local $a)) (get_local $c))))
    (if (f64.lt (get_local $d) (f64.const 0.0))
      (then
        (i32.store (get_local $p_status) (i32.const 0))
        (return)))
    (if (f64.eq (get_local $d) (f64.const 0.0))
      (then
        (f64.store (get_local $roots) (f64.div (f64.div (f64.neg (get_local $b)) (f64.const 2.0)) (get_local $a)))
        (f64.store (i32.add (get_local $roots) (i32.const 8)) (f64.div (f64.div (f64.neg (get_local $b)) (f64.const 2.0)) (get_local $a)))
        (i32.store (get_local $p_status) (i32.const 1))
        (return)))
    (set_local $sqrt_d (f64.sqrt (get_local $d)))
    (f64.store (get_local $roots) (f64.div (f64.div (f64.sub (f64.neg (get_local $b)) (get_local $sqrt_d)) (f64.const 2.0)) (get_local $a)))
    (f64.store (i32.add (get_local $roots) (i32.const 8)) (f64.div (f64.div (f64.add (f64.neg (get_local $b)) (get_local $sqrt_d)) (f64.const 2.0)) (get_local $a)))
    (i32.store (get_local $p_status) (i32.const 2)))
  (func $try_solving (param $a i32) (param $b i32) (param $c i32)
    (local $@stack_entry i32)
    (local $roots i32)
    (local $p_status i32)
    (set_local $@stack_entry (global.get $@stack))
    (set_local $roots (call $malloc (i32.const 16)))
    (set_local $p_status (call $malloc (i32.const 4)))
    (call $solve_square_equation (f64.convert_i32_s (get_local $a)) (f64.convert_i32_s (get_local $b)) (f64.convert_i32_s (get_local $c)) (get_local $roots) (get_local $p_status))
    (i64.store (global.get $@stack) (i64.extend_i32_s (get_local $a)))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (i64.store (global.get $@stack) (i64.extend_i32_s (get_local $b)))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (i64.store (global.get $@stack) (i64.extend_i32_s (get_local $c)))
    (global.set $@stack (i32.sub (global.get $@stack) (i32.const 16)))
    (call $printf (i32.const 1024) (global.get $@stack))
    (if (i32.eqz (i32.load (get_local $p_status)))
      (then
        (call $printf (i32.const 1049) (global.get $@stack)))
      (else
        (if (i32.eq (i32.load (get_local $p_status)) (i32.const 1))
          (then
            (f64.store (global.get $@stack) (f64.load (get_local $roots)))
            (call $printf (i32.const 1059) (global.get $@stack)))
          (else
            (if (i32.eq (i32.load (get_local $p_status)) (i32.const 2))
              (then
                (f64.store (global.get $@stack) (f64.load (get_local $roots)))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (f64.store (global.get $@stack) (f64.load (i32.add (get_local $roots) (i32.const 8))))
                (global.set $@stack (i32.sub (global.get $@stack) (i32.const 8)))
                (call $printf (i32.const 1074) (global.get $@stack))))))))
    (call $free (get_local $roots))
    (call $free (get_local $p_status))
    (global.set $@stack (get_local $@stack_entry)))
  (func $main (export "main") (result i32)
    (call $try_solving (i32.const 1) (i32.const -2) (i32.const 1))
    (call $try_solving (i32.const 10) (i32.const 11) (i32.const -7))
    (call $try_solving (i32.const 10) (i32.const 11) (i32.const 7))
    (i32.const 0))
  (func $malloc (param $size i32) (result i32)
    (local $res i32)
    (local $pages i32)
    (if (i32.lt_s (global.get $__available_size) (i32.const 0))
      (then
        (global.set $__available_size (i32.mul (i32.const 64000) (memory.size)))))
    (set_local $res (global.get $__last_offset))
    (global.set $__last_offset (i32.add (global.get $__last_offset) (get_local $size)))
    (if (i32.gt_s (global.get $__last_offset) (global.get $__available_size))
      (then
        (set_local $pages (i32.add (i32.const 1) (i32.div_s (global.get $__last_offset) (i32.const 64000))))
        (drop (memory.grow (i32.sub (get_local $pages) (memory.size))))
        (global.set $__available_size (i32.mul (i32.const 64000) (get_local $pages)))))
    (get_local $res))
  (func $free (param $ptr i32)))
