(module
  (import "c4wa" "printf" (func $printf (param i32) (param i32)))
  (global $@stack (mut i32) (i32.const 0))
  (global $__get_index_cnt (mut i32) (i32.const 0))
  (global $N (mut i32) (i32.const 100))
  (memory (export "memory") 1)
  (data (i32.const 1024) "[%d] Calling get_index()\0A\00a[%d] = %d, b[0] = %d\0A\00")
  (func $get_index (result i32)
    (local $@stack_entry i32)
    (set_local $@stack_entry (global.get $@stack))
    (global.set $__get_index_cnt (i32.add (global.get $__get_index_cnt) (i32.const 1)))
    (i64.store (global.get $@stack) (i64.extend_i32_s (global.get $__get_index_cnt)))
    (call $printf (i32.const 1024) (global.get $@stack))
    (global.set $@stack (get_local $@stack_entry))
    (i32.sub (global.get $N) (i32.const 1)))
  (func $main (export "main") (result i32)
    (local $@stack_entry i32)
    (local $a i32)
    (local $b i32)
    (local $i i32)
    (local $@temp_i32 i32)
    (set_local $@stack_entry (global.get $@stack))
    (set_local $a (global.get $@stack))
    (global.set $@stack (i32.add (global.get $@stack) (i32.mul (global.get $N) (i32.const 4))))
    (set_local $b (global.get $@stack))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 40)))
    (block $@block_1_break
      (loop $@block_1_continue
        (br_if $@block_1_break (i32.ge_s (get_local $i) (global.get $N)))
        (i32.store (i32.add (get_local $a) (i32.mul (get_local $i) (i32.const 4))) (i32.const 10))
        (set_local $i (i32.add (get_local $i) (i32.const 1)))
        (br $@block_1_continue)))
    (i32.store (get_local $b) (i32.const 3))
    (memory.fill (get_local $a) (i32.const 0) (i32.mul (global.get $N) (i32.const 4)))
    (set_local $@temp_i32 (i32.add (get_local $a) (i32.mul (call $get_index) (i32.const 4))))
    (i32.store (get_local $@temp_i32) (i32.add (i32.load (get_local $@temp_i32)) (i32.const 1)))
    (i32.store (get_local $b) (i32.or (i32.load (get_local $b)) (i32.const 1024)))
    (i64.store (global.get $@stack) (i64.extend_i32_s (call $get_index)))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (i64.store (global.get $@stack) (i64.extend_i32_s (i32.load (i32.add (get_local $a) (i32.mul (call $get_index) (i32.const 4))))))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (i64.store (global.get $@stack) (i64.extend_i32_s (i32.load (get_local $b))))
    (global.set $@stack (i32.sub (global.get $@stack) (i32.const 16)))
    (call $printf (i32.const 1050) (global.get $@stack))
    (global.set $@stack (get_local $@stack_entry))
    (i32.const 0)))
