(module
  (import "c4wa" "printf" (func $printf (param i32) (param i32)))
  (global $@stack (mut i32) (i32.const 1))
  (memory (export "memory") 1)
  (data (i32.const 1024) "longNumber = %ld, floatNumber = %.6f\0A\00intNumber = %d, doubleNumber = %.6f\0A\00")
  (func $main (export "main") (result i32)
    (local $@stack_entry i32)
    (local $longNumber i64)
    (local $floatNumber f32)
    (local $intNumber i32)
    (local $doubleNumber f64)
    (set_local $@stack_entry (global.get $@stack))
    (set_local $longNumber (i64.const -18))
    (set_local $floatNumber (f32.const 123.4))
    (i64.store (global.get $@stack) (get_local $longNumber))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (f64.store (global.get $@stack) (f64.promote_f32 (get_local $floatNumber)))
    (global.set $@stack (i32.sub (global.get $@stack) (i32.const 8)))
    (call $printf (i32.const 1024) (global.get $@stack))
    (set_local $intNumber (i32.const -57))
    (set_local $doubleNumber (f64.const 11.0))
    (i64.store (global.get $@stack) (i64.extend_i32_s (get_local $intNumber)))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (f64.store (global.get $@stack) (get_local $doubleNumber))
    (global.set $@stack (i32.sub (global.get $@stack) (i32.const 8)))
    (call $printf (i32.const 1062) (global.get $@stack))
    (global.set $@stack (get_local $@stack_entry))
    (i32.const 0)))
