(module
  (import "c4wa" "printf" (func $printf (param i32) (param i32)))
  (global $v (mut i32) (i32.const -1))
  (global $@stack (mut i32) (i32.const 1))
  (memory (export "memory") 1)
  (data (i32.const 1024) "global v = %d\0A\00v@main = %d\0A\00")
  (func $print_global_v
    (local $@stack_entry i32)
    (set_local $@stack_entry (global.get $@stack))
    (i64.store (global.get $@stack) (i64.extend_i32_s (global.get $v)))
    (call $printf (i32.const 1024) (global.get $@stack))
    (global.set $@stack (get_local $@stack_entry)))
  (func $main (export "main") (result i32)
    (local $@stack_entry i32)
    (local $v i32)
    (set_local $@stack_entry (global.get $@stack))
    (call $print_global_v)
    (i64.store (global.get $@stack) (i64.extend_i32_s (global.get $v)))
    (call $printf (i32.const 1039) (global.get $@stack))
    (set_local $v (i32.const 18))
    (call $print_global_v)
    (i64.store (global.get $@stack) (i64.extend_i32_s (get_local $v)))
    (call $printf (i32.const 1039) (global.get $@stack))
    (global.set $@stack (get_local $@stack_entry))
    (i32.const 0)))
