(module
  (import "c4wa" "printf" (func $printf (param i32) (param i32)))
  (global $@stack (mut i32) (i32.const 8))
  (memory (export "memory") 1)
  (data (i32.const 1024) "\E2\88\9A%d = %.6f = %.6lf\0A\00")
  (func $main (export "main") (result i32)
    (local $@stack_entry i32)
    (local $i i32)
    (local $fv f32)
    (local $dv f64)
    (set_local $@stack_entry (global.get $@stack))
    (block $@block_1_break
      (loop $@block_1_continue
        (br_if $@block_1_break (i32.ge_s (get_local $i) (i32.const 10)))
        (set_local $dv (f64.convert_i32_s (get_local $i)))
        (set_local $fv (f32.convert_i32_s (get_local $i)))
        (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (get_local $i)))
        (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
        (f64.store align=8 (global.get $@stack) (f64.promote_f32 (f32.sqrt (get_local $fv))))
        (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
        (f64.store align=8 (global.get $@stack) (f64.sqrt (get_local $dv)))
        (global.set $@stack (i32.sub (global.get $@stack) (i32.const 16)))
        (call $printf (i32.const 1024) (global.get $@stack))
        (set_local $i (i32.add (get_local $i) (i32.const 1)))
        (br $@block_1_continue)))
    (global.set $@stack (get_local $@stack_entry))
    (i32.const 0)))
