(module
  (import "c4wa" "printf" (func $printf (param i32) (param i32)))
  (global $__mm_capacity (mut i32) (i32.const 0))
  (global $__mm_stat_freed (mut i32) (i32.const 0))
  (global $__mm_inuse (mut i32) (i32.const 0))
  (global $__mm_expand_by (mut i32) (i32.const 10))
  (global $__mm_start (mut i32) (i32.const 0))
  (global $__mm_extra_offset (mut i32) (i32.const -1))
  (global $__mm_stat_allocated (mut i32) (i32.const 0))
  (global $@stack (mut i32) (i32.const 0))
  (global $__mm_first (mut i32) (i32.const -1))
  (global $__mm_size (mut i32) (i32.const -1))
  (global $M i32 (i32.const 13))
  (memory (export "memory") 1)
  (data (i32.const 1024) "red\00green\00blue\00unknown\00A[%s] = %.6f, %.6f, %.6f\0A\00B[%s] = %.6f, %.6f, %.6f\0A\00C[%s] = %.6f, %.6f, %.6f\0A\00sin(\E2\8D\BA) = %.6f, cos(\E2\8D\BA) = %.6f\0A\00sin(\E2\8D\BA)^2 + cos(\E2\8D\BA)^2 = %.6f\0A\00")
  (func $dot (param $A i32) (param $B i32) (result f64)
    (f64.promote_f32 (f32.add (f32.add (f32.mul (f32.load (get_local $A)) (f32.load (get_local $B))) (f32.mul (f32.load (i32.add (get_local $A) (i32.const 4))) (f32.load (i32.add (get_local $B) (i32.const 4))))) (f32.mul (f32.load (i32.add (get_local $A) (i32.const 9))) (f32.load (i32.add (get_local $B) (i32.const 9)))))))
  (func $len (param $p i32) (result f64)
    (f64.sqrt (call $dot (get_local $p) (get_local $p))))
  (func $cross (param $A i32) (param $B i32) (param $C i32)
    (f32.store (get_local $C) (f32.sub (f32.mul (f32.load (i32.add (get_local $A) (i32.const 4))) (f32.load (i32.add (get_local $B) (i32.const 9)))) (f32.mul (f32.load (i32.add (get_local $A) (i32.const 9))) (f32.load (i32.add (get_local $B) (i32.const 4))))))
    (f32.store (i32.add (get_local $C) (i32.const 4)) (f32.sub (f32.mul (f32.load (i32.add (get_local $A) (i32.const 9))) (f32.load (get_local $B))) (f32.mul (f32.load (get_local $A)) (f32.load (i32.add (get_local $B) (i32.const 9))))))
    (f32.store (i32.add (get_local $C) (i32.const 9)) (f32.sub (f32.mul (f32.load (get_local $A)) (f32.load (i32.add (get_local $B) (i32.const 4)))) (f32.mul (f32.load (i32.add (get_local $A) (i32.const 4))) (f32.load (get_local $B))))))
  (func $color (param $p i32) (result i32)
    (if (result i32) (i32.eq (i32.load8_s (i32.add (get_local $p) (i32.const 8))) (i32.const 114)) (then (i32.const 1024)) (else (select (i32.const 1028) (select (i32.const 1034) (i32.const 1039) (i32.eq (i32.load8_s (i32.add (get_local $p) (i32.const 8))) (i32.const 98))) (i32.eq (i32.load8_s (i32.add (get_local $p) (i32.const 8))) (i32.const 103))))))
  (func $main (export "main") (result i32)
    (local $@stack_entry i32)
    (local $A i32)
    (local $B i32)
    (local $C i32)
    (local $cos_a f64)
    (local $sin_a f64)
    (set_local $@stack_entry (global.get $@stack))
    (set_local $A (call $malloc (global.get $M)))
    (set_local $B (call $malloc (global.get $M)))
    (set_local $C (call $malloc (global.get $M)))
    (f32.store (get_local $A) (f32.const 1.0))
    (f32.store (i32.add (get_local $A) (i32.const 4)) (f32.const -2.0))
    (f32.store (i32.add (get_local $A) (i32.const 9)) (f32.const 3.0))
    (i32.store8 (i32.add (get_local $A) (i32.const 8)) (i32.const 114))
    (f32.store (get_local $B) (f32.const 4.0))
    (f32.store (i32.add (get_local $B) (i32.const 4)) (f32.const 5.0))
    (f32.store (i32.add (get_local $B) (i32.const 9)) (f32.const -6.0))
    (i32.store8 (i32.add (get_local $B) (i32.const 8)) (i32.const 103))
    (i32.store8 (i32.add (get_local $C) (i32.const 8)) (i32.const 98))
    (call $cross (get_local $A) (get_local $B) (get_local $C))
    (set_local $cos_a (f64.div (f64.div (call $dot (get_local $A) (get_local $B)) (call $len (get_local $A))) (call $len (get_local $B))))
    (set_local $sin_a (f64.div (f64.div (call $len (get_local $C)) (call $len (get_local $A))) (call $len (get_local $B))))
    (i64.store (global.get $@stack) (i64.const 1047))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (i64.store (global.get $@stack) (i64.extend_i32_s (call $color (get_local $A))))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (f64.store (global.get $@stack) (f64.promote_f32 (f32.load (get_local $A))))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (f64.store (global.get $@stack) (f64.promote_f32 (f32.load (i32.add (get_local $A) (i32.const 4)))))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (f64.store (global.get $@stack) (f64.promote_f32 (f32.load (i32.add (get_local $A) (i32.const 9)))))
    (global.set $@stack (i32.sub (global.get $@stack) (i32.const 32)))
    (call $printf (global.get $@stack) (i32.const 5))
    (i64.store (global.get $@stack) (i64.const 1073))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (i64.store (global.get $@stack) (i64.extend_i32_s (call $color (get_local $B))))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (f64.store (global.get $@stack) (f64.promote_f32 (f32.load (get_local $B))))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (f64.store (global.get $@stack) (f64.promote_f32 (f32.load (i32.add (get_local $B) (i32.const 4)))))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (f64.store (global.get $@stack) (f64.promote_f32 (f32.load (i32.add (get_local $B) (i32.const 9)))))
    (global.set $@stack (i32.sub (global.get $@stack) (i32.const 32)))
    (call $printf (global.get $@stack) (i32.const 5))
    (i64.store (global.get $@stack) (i64.const 1099))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (i64.store (global.get $@stack) (i64.extend_i32_s (call $color (get_local $C))))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (f64.store (global.get $@stack) (f64.promote_f32 (f32.load (get_local $C))))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (f64.store (global.get $@stack) (f64.promote_f32 (f32.load (i32.add (get_local $C) (i32.const 4)))))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (f64.store (global.get $@stack) (f64.promote_f32 (f32.load (i32.add (get_local $C) (i32.const 9)))))
    (global.set $@stack (i32.sub (global.get $@stack) (i32.const 32)))
    (call $printf (global.get $@stack) (i32.const 5))
    (i64.store (global.get $@stack) (i64.const 1125))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (f64.store (global.get $@stack) (get_local $sin_a))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (f64.store (global.get $@stack) (get_local $cos_a))
    (global.set $@stack (i32.sub (global.get $@stack) (i32.const 16)))
    (call $printf (global.get $@stack) (i32.const 3))
    (i64.store (global.get $@stack) (i64.const 1159))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (f64.store (global.get $@stack) (f64.add (f64.mul (get_local $sin_a) (get_local $sin_a)) (f64.mul (get_local $cos_a) (get_local $cos_a))))
    (global.set $@stack (i32.sub (global.get $@stack) (i32.const 8)))
    (call $printf (global.get $@stack) (i32.const 2))
    (global.set $@stack (get_local $@stack_entry))
    (i32.const 0))
  (func $mm_init (param $extra_offset i32) (param $size i32)
    (if (block $@block_1_break (result i32) (drop (br_if $@block_1_break (i32.const 1) (i32.lt_s (get_local $extra_offset) (i32.const 0)))) (drop (br_if $@block_1_break (i32.const 1) (i32.lt_s (get_local $size) (i32.const 1)))) (drop (br_if $@block_1_break (i32.const 1) (global.get $__mm_start))) (i32.const 0))
      (then
        (unreachable)))
    (global.set $__mm_extra_offset (get_local $extra_offset))
    (global.set $__mm_size (get_local $size))
    (global.set $__mm_start (i32.add (i32.const 1191) (global.get $__mm_extra_offset))))
  (func $malloc (param $size i32) (result i32)
    (local $unit_size i32)
    (local $required i32)
    (local $j i32)
    (local $result i32)
    (global.set $__mm_stat_allocated (i32.add (global.get $__mm_stat_allocated) (i32.const 1)))
    (if (i32.eqz (global.get $__mm_start))
      (then
        (call $mm_init (i32.const 0) (get_local $size))))
    (if (i32.gt_s (get_local $size) (global.get $__mm_size))
      (then
        (unreachable)))
    (set_local $unit_size (i32.add (i32.const 1) (i32.mul (i32.const 8) (global.get $__mm_size))))
    (if (if (result i32) (i32.ge_s (global.get $__mm_first) (i32.const 0)) (then (i32.const 0)) (else (i32.ne (i32.eq (global.get $__mm_inuse) (global.get $__mm_capacity)) (i32.const 0))))
      (then
        (set_local $required (i32.add (i32.div_s (i32.add (i32.add (i32.const 1191) (global.get $__mm_extra_offset)) (i32.mul (i32.mul (i32.add (global.get $__mm_capacity) (global.get $__mm_expand_by)) (i32.const 8)) (get_local $unit_size))) (i32.const 64000)) (i32.const 1)))
        (if (i32.gt_s (get_local $required) (memory.size))
          (then
            (drop (memory.grow (i32.sub (get_local $required) (memory.size))))))
        (global.set $__mm_capacity (i32.add (global.get $__mm_capacity) (global.get $__mm_expand_by)))))
    (if (i32.lt_s (global.get $__mm_first) (i32.const 0))
      (then
        (if (i32.ge_s (global.get $__mm_inuse) (global.get $__mm_capacity))
          (then
            (unreachable)))
        (i64.store (i32.add (global.get $__mm_start) (i32.mul (i32.mul (global.get $__mm_inuse) (get_local $unit_size)) (i32.const 8))) (i64.const -1))
        (global.set $__mm_first (global.get $__mm_inuse))
        (global.set $__mm_inuse (i32.add (global.get $__mm_inuse) (i32.const 1)))))
    (if (i32.lt_s (global.get $__mm_first) (i32.const 0))
      (then
        (unreachable)))
    (set_local $required (i32.add (global.get $__mm_start) (i32.mul (i32.mul (global.get $__mm_first) (get_local $unit_size)) (i32.const 8))))
    (if (i64.eq (i64.load (get_local $required)) (i64.const 0))
      (then
        (unreachable)))
    (set_local $j (i32.wrap_i64 (i64.ctz (i64.load (get_local $required)))))
    (i64.store (get_local $required) (i64.xor (i64.load (get_local $required)) (i64.shl (i64.const 1) (i64.extend_i32_s (get_local $j)))))
    (set_local $result (i32.add (i32.add (get_local $required) (i32.const 8)) (i32.mul (get_local $j) (global.get $__mm_size))))
    (if (i64.eqz (i64.load (get_local $required)))
      (then
        (loop $@block_3_1_continue
          (global.set $__mm_first (i32.add (global.get $__mm_first) (i32.const 1)))
          (br_if $@block_3_1_continue (if (result i32) (i32.ge_s (global.get $__mm_first) (global.get $__mm_inuse)) (then (i32.const 0)) (else (i32.ne (i64.eqz (i64.load (i32.add (global.get $__mm_start) (i32.mul (i32.mul (global.get $__mm_first) (get_local $unit_size)) (i32.const 8))))) (i32.const 0))))))
        (if (i32.eq (global.get $__mm_first) (global.get $__mm_inuse))
          (then
            (global.set $__mm_first (i32.const -1))))))
    (get_local $result)))
