(module
  (import "c4wa" "printf" (func $printf (param i32) (param i32)))
  (global $seed (mut i32) (i32.const 57))
  (global $__mm_memory (mut i32) (i32.const 0))
  (global $__mm_stat_freed (mut i32) (i32.const 0))
  (global $__mm_inuse (mut i32) (i32.const 0))
  (global $__mm_avail (mut i32) (i32.const 0))
  (global $__mm_stat_allocated (mut i32) (i32.const 0))
  (global $__mm_extra_offset (mut i32) (i32.const -1))
  (global $@stack (mut i32) (i32.const 0))
  (global $storage (mut i32) (i32.const 0))
  (global $__mm_min (mut i32) (i32.const 0))
  (memory (export "memory") 1)
  (data (i32.const 1024) "malloc(%d)\0A\00Allocating %d big blocks\0A\00Found free stretch from %d to %d\0A\00\E2\80\BC\EF\B8\8F ASSERTION: \22idx <= __mm_inuse\22 @ line %d\0A\00Need %d more units\0A\00\E2\80\BC\EF\B8\8F ASSERTION: \22need > 0\22 @ line %d\0A\00\E2\80\BC\EF\B8\8F ASSERTION: \22need <= n\22 @ line %d\0A\00Need %d more page(s) in addition to currently allocated %d\0A\00Bumping __mm_inuse from %d to %d\0A\00Following expansion, returning stretch from %d to %d\0A\00\E2\80\BC\EF\B8\8F ASSERTION: \22n <= 6\22 @ line %d\0A\00Actual size %d, n = %d, idx = %d\0A\00\E2\80\BC\EF\B8\8F ASSERTION: \22idx >= 0\22 @ line %d\0A\00Bumping __mm_inuse to %d\0A\00Found available space at unit %d [%s]\0A\00not initialized\00initialized\00Setting __mm_avail[%d] = %d\0A\00\E2\80\BC\EF\B8\8F ASSERTION: \22state == 0 || state == n + 1\22 @ line %d\0A\00Initializing unit %d to n = %d (actual size = %d) | %lx\0A\00\E2\80\BC\EF\B8\8F ASSERTION: \22*cur != 0\22 @ line %d\0A\00Using internal index %d\0A\00Unit at index %d is exhausted, setting __mm_avail[%d] = -1\0A\00\E2\80\BC\EF\B8\8F ASSERTION: \22state != 0\22 @ line %d\0A\00free::large[%d]<%d units>\0A\00\E2\80\BC\EF\B8\8F ASSERTION: \22address == __mm_memory + idx * unit + 4\22 @ line %d\0A\00free::small[%d](<size %d (n = %d), j = %d>\0A\00\E2\80\BC\EF\B8\8F ASSERTION: \22j >= 0 && j < bits\22 @ line %d\0A\00\E2\80\BC\EF\B8\8F ASSERTION: \22address == (char *)cur + 8 + j * a_size\22 @ line %d\0A\00\E2\80\BC\EF\B8\8F ASSERTION: \22(*cur & (unsigned long)1 << (unsigned long)j) == 0\22 @ line %d\0A\00Not changing __mm_avail[%d] == %d\0A\00\E2\80\BC\EF\B8\8F ASSERTION: \221 <= __builtin_popcountl(*cur)\22 @ line %d\0A\00\E2\80\BC\EF\B8\8F ASSERTION: \22__builtin_popcountl(*cur) <= bits\22 @ line %d\0A\00__mm_avail[%d] = %d != %d; *cur = %lx; seems like we can reset state from %d to 0\0A\00A\00B<%d>\0A\00S<%d|free=%d>\00\0A\00\E2\80\BC\EF\B8\8F ASSERTION: \22unit->integrity == (unit->id ^ 816191)\22 @ line %d\0A\00Starting memory test with %d empty \22unit\22 pointers and %d iterations\0A\00Finished fixed memory test\0A\00")
  (func $mm_init (param $mm_min i32)
    (local $i i32)
    (if (global.get $__mm_min)
      (then
        (unreachable)))
    (global.set $__mm_min (get_local $mm_min))
    (global.set $__mm_extra_offset (i32.const 40))
    (global.set $__mm_memory (i32.add (i32.const 2696) (global.get $__mm_extra_offset)))
    (global.set $__mm_avail (i32.const 2696))
    (block $@block_1_break
      (loop $@block_1_continue
        (br_if $@block_1_break (i32.gt_s (get_local $i) (i32.const 6)))
        (i32.store (i32.add (global.get $__mm_avail) (i32.mul (get_local $i) (i32.const 4))) (i32.const -1))
        (set_local $i (i32.add (get_local $i) (i32.const 1)))
        (br $@block_1_continue))))
  (func $mm_malloc (param $size i32) (result i32)
    (local $@stack_entry i32)
    (local $verbose i32)
    (local $i i32)
    (local $j i32)
    (local $n i32)
    (local $m i32)
    (local $idx i32)
    (local $state i32)
    (local $required i32)
    (local $unit i32)
    (local $need i32)
    (local $a_size i32)
    (local $bits i32)
    (local $cur i32)
    (set_local $@stack_entry (global.get $@stack))
    (global.set $__mm_stat_allocated (i32.add (global.get $__mm_stat_allocated) (i32.const 1)))
    (if (i32.eqz (global.get $__mm_min))
      (then
        (call $mm_init (i32.const 128))))
    (set_local $unit (i32.add (i32.mul (i32.const 64) (global.get $__mm_min)) (i32.const 12)))
    (if (get_local $verbose)
      (then
        (i64.store (global.get $@stack) (i64.const 1024))
        (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
        (i64.store (global.get $@stack) (i64.extend_i32_s (get_local $size)))
        (global.set $@stack (i32.sub (global.get $@stack) (i32.const 8)))
        (call $printf (global.get $@stack) (i32.const 2))))
    (if (i32.gt_s (get_local $size) (i32.mul (i32.const 64) (global.get $__mm_min)))
      (then
        (set_local $n (i32.add (i32.const 1) (i32.div_s (i32.sub (get_local $size) (i32.add (i32.mul (i32.const 64) (global.get $__mm_min)) (i32.const 8))) (i32.add (i32.mul (i32.const 64) (global.get $__mm_min)) (i32.const 12)))))
        (if (get_local $verbose)
          (then
            (i64.store (global.get $@stack) (i64.const 1036))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store (global.get $@stack) (i64.extend_i32_s (get_local $n)))
            (global.set $@stack (i32.sub (global.get $@stack) (i32.const 8)))
            (call $printf (global.get $@stack) (i32.const 2))))
        (set_local $idx (i32.const 0))
        (block $@block_1_break
          (loop $@block_1_continue
            (br_if $@block_1_break (i32.ge_s (get_local $idx) (global.get $__mm_inuse)))
            (set_local $state (i32.load (i32.add (global.get $__mm_memory) (i32.mul (get_local $idx) (get_local $unit)))))
            (if (i32.eqz (get_local $state))
              (then
                (block $@block_1_2_break
                  (set_local $j (i32.add (get_local $idx) (i32.const 1)))
                  (loop $@block_1_2_continue
                    (br_if $@block_1_2_break (i32.eqz (block $@block_1_1_break (result i32) (drop (br_if $@block_1_1_break (i32.const 0) (i32.ge_s (get_local $j) (global.get $__mm_inuse)))) (drop (br_if $@block_1_1_break (i32.const 0) (i32.ge_s (get_local $j) (i32.add (get_local $i) (get_local $n))))) (drop (br_if $@block_1_1_break (i32.const 0) (i32.load (i32.add (global.get $__mm_memory) (i32.mul (get_local $j) (get_local $unit)))))) (i32.const 1))))
                    (set_local $j (i32.add (get_local $j) (i32.const 1)))
                    (br $@block_1_2_continue)))
                (if (i32.ge_s (i32.sub (get_local $j) (get_local $i)) (get_local $n))
                  (then
                    (if (get_local $verbose)
                      (then
                        (i64.store (global.get $@stack) (i64.const 1062))
                        (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                        (i64.store (global.get $@stack) (i64.extend_i32_s (get_local $idx)))
                        (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                        (i64.store (global.get $@stack) (i64.extend_i32_s (i32.sub (get_local $j) (i32.const 1))))
                        (global.set $@stack (i32.sub (global.get $@stack) (i32.const 16)))
                        (call $printf (global.get $@stack) (i32.const 3))))
                    (i32.store (i32.add (global.get $__mm_memory) (i32.mul (get_local $idx) (get_local $unit))) (i32.sub (i32.const 0) (get_local $n)))
                    (global.set $@stack (get_local $@stack_entry))
                    (return (i32.add (global.get $__mm_memory) (i32.mul (get_local $idx) (get_local $unit))))))
                (br_if $@block_1_break (i32.eq (get_local $j) (global.get $__mm_inuse)))
                (set_local $idx (get_local $j)))
              (else
                (if (i32.lt_s (get_local $state) (i32.const 0))
                  (then
                    (set_local $idx (i32.add (get_local $idx) (i32.sub (i32.const 0) (get_local $state)))))
                  (else
                    (set_local $idx (i32.add (get_local $idx) (i32.const 1)))))))
            (br $@block_1_continue)))
        (if (i32.gt_s (get_local $idx) (global.get $__mm_inuse))
          (then
            (i64.store (global.get $@stack) (i64.const 1096))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store (global.get $@stack) (i64.const 135))
            (global.set $@stack (i32.sub (global.get $@stack) (i32.const 8)))
            (call $printf (global.get $@stack) (i32.const 2))
            (unreachable)))
        (set_local $need (i32.sub (get_local $n) (i32.sub (global.get $__mm_inuse) (get_local $idx))))
        (if (get_local $verbose)
          (then
            (i64.store (global.get $@stack) (i64.const 1145))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store (global.get $@stack) (i64.extend_i32_s (get_local $need)))
            (global.set $@stack (i32.sub (global.get $@stack) (i32.const 8)))
            (call $printf (global.get $@stack) (i32.const 2))))
        (if (i32.le_s (get_local $need) (i32.const 0))
          (then
            (i64.store (global.get $@stack) (i64.const 1165))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store (global.get $@stack) (i64.const 140))
            (global.set $@stack (i32.sub (global.get $@stack) (i32.const 8)))
            (call $printf (global.get $@stack) (i32.const 2))
            (unreachable)))
        (if (i32.gt_s (get_local $need) (get_local $n))
          (then
            (i64.store (global.get $@stack) (i64.const 1205))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store (global.get $@stack) (i64.const 141))
            (global.set $@stack (i32.sub (global.get $@stack) (i32.const 8)))
            (call $printf (global.get $@stack) (i32.const 2))
            (unreachable)))
        (set_local $required (i32.add (i32.div_s (i32.add (i32.add (i32.const 2696) (global.get $__mm_extra_offset)) (i32.mul (i32.add (global.get $__mm_inuse) (get_local $need)) (get_local $unit))) (i32.const 64000)) (i32.const 1)))
        (if (i32.gt_s (get_local $required) (memory.size))
          (then
            (if (get_local $verbose)
              (then
                (i64.store (global.get $@stack) (i64.const 1246))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (i64.store (global.get $@stack) (i64.extend_i32_s (i32.sub (get_local $required) (memory.size))))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (i64.store (global.get $@stack) (i64.extend_i32_s (memory.size)))
                (global.set $@stack (i32.sub (global.get $@stack) (i32.const 16)))
                (call $printf (global.get $@stack) (i32.const 3))))
            (drop (memory.grow (i32.sub (get_local $required) (memory.size))))))
        (block $@block_2_break
          (set_local $i (i32.const 0))
          (loop $@block_2_continue
            (br_if $@block_2_break (i32.ge_s (get_local $i) (get_local $need)))
            (i32.store (i32.add (global.get $__mm_memory) (i32.mul (i32.add (get_local $i) (global.get $__mm_inuse)) (get_local $unit))) (i32.const 0))
            (set_local $i (i32.add (get_local $i) (i32.const 1)))
            (br $@block_2_continue)))
        (if (get_local $verbose)
          (then
            (i64.store (global.get $@stack) (i64.const 1306))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store (global.get $@stack) (i64.extend_i32_s (global.get $__mm_inuse)))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store (global.get $@stack) (i64.extend_i32_s (i32.add (global.get $__mm_inuse) (get_local $need))))
            (global.set $@stack (i32.sub (global.get $@stack) (i32.const 16)))
            (call $printf (global.get $@stack) (i32.const 3))))
        (global.set $__mm_inuse (i32.add (global.get $__mm_inuse) (get_local $need)))
        (if (get_local $verbose)
          (then
            (i64.store (global.get $@stack) (i64.const 1340))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store (global.get $@stack) (i64.extend_i32_s (get_local $idx)))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store (global.get $@stack) (i64.extend_i32_s (i32.sub (i32.add (get_local $idx) (get_local $n)) (i32.const 1))))
            (global.set $@stack (i32.sub (global.get $@stack) (i32.const 16)))
            (call $printf (global.get $@stack) (i32.const 3))))
        (i32.store (i32.add (global.get $__mm_memory) (i32.mul (get_local $idx) (get_local $unit))) (i32.sub (i32.const 0) (get_local $n)))
        (global.set $@stack (get_local $@stack_entry))
        (return (i32.add (global.get $__mm_memory) (i32.mul (get_local $idx) (get_local $unit)))))
      (else
        (set_local $a_size (global.get $__mm_min))
        (block $@block_3_break
          (set_local $n (i32.const 0))
          (loop $@block_3_continue
            (br_if $@block_3_break (i32.ge_s (get_local $a_size) (get_local $size)))
            (if (i32.gt_s (get_local $n) (i32.const 6))
              (then
                (i64.store (global.get $@stack) (i64.const 1394))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (i64.store (global.get $@stack) (i64.const 162))
                (global.set $@stack (i32.sub (global.get $@stack) (i32.const 8)))
                (call $printf (global.get $@stack) (i32.const 2))
                (unreachable)))
            (set_local $n (i32.add (get_local $n) (i32.const 1)))
            (set_local $a_size (i32.mul (get_local $a_size) (i32.const 2)))
            (br $@block_3_continue)))
        (set_local $idx (i32.load (i32.add (global.get $__mm_avail) (i32.mul (get_local $n) (i32.const 4)))))
        (if (get_local $verbose)
          (then
            (i64.store (global.get $@stack) (i64.const 1432))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store (global.get $@stack) (i64.extend_i32_s (get_local $a_size)))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store (global.get $@stack) (i64.extend_i32_s (get_local $n)))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store (global.get $@stack) (i64.extend_i32_s (get_local $idx)))
            (global.set $@stack (i32.sub (global.get $@stack) (i32.const 24)))
            (call $printf (global.get $@stack) (i32.const 4))))
        (if (i32.lt_s (get_local $idx) (i32.const 0))
          (then
            (set_local $idx (i32.const 0))
            (block $@block_4_break
              (loop $@block_4_continue
                (br_if $@block_4_break (i32.ge_s (get_local $idx) (global.get $__mm_inuse)))
                (set_local $state (i32.load (i32.add (global.get $__mm_memory) (i32.mul (get_local $idx) (get_local $unit)))))
                (if (if (result i32) (i32.eqz (get_local $state)) (then (i32.const 1)) (else (i32.ne (if (result i32) (i32.ne (get_local $state) (i32.add (get_local $n) (i32.const 1))) (then (i32.const 0)) (else (i32.ne (i64.ne (i64.load (i32.add (i32.add (global.get $__mm_memory) (i32.mul (get_local $idx) (get_local $unit))) (i32.const 4))) (i64.const 0)) (i32.const 0)))) (i32.const 0))))
                  (then
                    (br $@block_4_break))
                  (else
                    (if (i32.gt_s (get_local $state) (i32.const 0))
                      (then
                        (set_local $idx (i32.add (get_local $idx) (i32.const 1))))
                      (else
                        (set_local $idx (i32.add (get_local $idx) (i32.sub (i32.const 0) (get_local $state))))))))
                (br $@block_4_continue)))
            (if (i32.lt_s (get_local $idx) (i32.const 0))
              (then
                (i64.store (global.get $@stack) (i64.const 1466))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (i64.store (global.get $@stack) (i64.const 180))
                (global.set $@stack (i32.sub (global.get $@stack) (i32.const 8)))
                (call $printf (global.get $@stack) (i32.const 2))
                (unreachable)))
            (if (i32.gt_s (get_local $idx) (global.get $__mm_inuse))
              (then
                (i64.store (global.get $@stack) (i64.const 1096))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (i64.store (global.get $@stack) (i64.const 181))
                (global.set $@stack (i32.sub (global.get $@stack) (i32.const 8)))
                (call $printf (global.get $@stack) (i32.const 2))
                (unreachable)))
            (if (i32.eq (get_local $idx) (global.get $__mm_inuse))
              (then
                (set_local $required (i32.add (i32.div_s (i32.add (i32.add (i32.const 2696) (global.get $__mm_extra_offset)) (i32.mul (i32.add (global.get $__mm_inuse) (i32.const 1)) (get_local $unit))) (i32.const 64000)) (i32.const 1)))
                (if (i32.gt_s (get_local $required) (memory.size))
                  (then
                    (if (get_local $verbose)
                      (then
                        (i64.store (global.get $@stack) (i64.const 1246))
                        (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                        (i64.store (global.get $@stack) (i64.extend_i32_s (i32.sub (get_local $required) (memory.size))))
                        (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                        (i64.store (global.get $@stack) (i64.extend_i32_s (memory.size)))
                        (global.set $@stack (i32.sub (global.get $@stack) (i32.const 16)))
                        (call $printf (global.get $@stack) (i32.const 3))))
                    (drop (memory.grow (i32.sub (get_local $required) (memory.size))))))
                (global.set $__mm_inuse (i32.add (global.get $__mm_inuse) (i32.const 1)))
                (if (get_local $verbose)
                  (then
                    (i64.store (global.get $@stack) (i64.const 1506))
                    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                    (i64.store (global.get $@stack) (i64.extend_i32_s (global.get $__mm_inuse)))
                    (global.set $@stack (i32.sub (global.get $@stack) (i32.const 8)))
                    (call $printf (global.get $@stack) (i32.const 2))))
                (i32.store (i32.add (global.get $__mm_memory) (i32.mul (get_local $idx) (get_local $unit))) (i32.const 0))))
            (if (get_local $verbose)
              (then
                (i64.store (global.get $@stack) (i64.const 1532))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (i64.store (global.get $@stack) (i64.extend_i32_s (get_local $idx)))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (i64.store (global.get $@stack) (i64.extend_i32_s (select (i32.const 1571) (i32.const 1587) (i32.eqz (i32.load (i32.add (global.get $__mm_memory) (i32.mul (get_local $idx) (get_local $unit))))))))
                (global.set $@stack (i32.sub (global.get $@stack) (i32.const 16)))
                (call $printf (global.get $@stack) (i32.const 3))))
            (if (get_local $verbose)
              (then
                (i64.store (global.get $@stack) (i64.const 1599))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (i64.store (global.get $@stack) (i64.extend_i32_s (get_local $n)))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (i64.store (global.get $@stack) (i64.extend_i32_s (get_local $idx)))
                (global.set $@stack (i32.sub (global.get $@stack) (i32.const 16)))
                (call $printf (global.get $@stack) (i32.const 3))))
            (i32.store (i32.add (global.get $__mm_avail) (i32.mul (get_local $n) (i32.const 4))) (get_local $idx))))
        (set_local $state (i32.load (i32.add (global.get $__mm_memory) (i32.mul (get_local $idx) (get_local $unit)))))
        (if (i32.eqz (if (result i32) (i32.eqz (get_local $state)) (then (i32.const 1)) (else (i32.ne (i32.eq (get_local $state) (i32.add (get_local $n) (i32.const 1))) (i32.const 0)))))
          (then
            (i64.store (global.get $@stack) (i64.const 1628))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store (global.get $@stack) (i64.const 203))
            (global.set $@stack (i32.sub (global.get $@stack) (i32.const 8)))
            (call $printf (global.get $@stack) (i32.const 2))
            (unreachable)))
        (if (i32.eqz (get_local $state))
          (then
            (i32.store (i32.add (global.get $__mm_memory) (i32.mul (get_local $idx) (get_local $unit))) (i32.add (get_local $n) (i32.const 1)))
            (set_local $bits (i32.shl (i32.const 1) (i32.sub (i32.const 6) (get_local $n))))
            (i64.store (i32.add (i32.add (global.get $__mm_memory) (i32.mul (get_local $idx) (get_local $unit))) (i32.const 4)) (i64.sub (select (i64.const 0) (i64.shl (i64.const 1) (i64.extend_i32_s (get_local $bits))) (i32.eq (get_local $bits) (i32.const 64))) (i64.const 1)))
            (if (get_local $verbose)
              (then
                (i64.store (global.get $@stack) (i64.const 1688))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (i64.store (global.get $@stack) (i64.extend_i32_s (get_local $idx)))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (i64.store (global.get $@stack) (i64.extend_i32_s (get_local $n)))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (i64.store (global.get $@stack) (i64.extend_i32_s (get_local $a_size)))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (i64.store (global.get $@stack) (i64.load (i32.add (i32.add (global.get $__mm_memory) (i32.mul (get_local $idx) (get_local $unit))) (i32.const 4))))
                (global.set $@stack (i32.sub (global.get $@stack) (i32.const 32)))
                (call $printf (global.get $@stack) (i32.const 5))))))
        (set_local $cur (i32.add (i32.add (global.get $__mm_memory) (i32.mul (get_local $idx) (get_local $unit))) (i32.const 4)))
        (if (i64.eq (i64.load (get_local $cur)) (i64.const 0))
          (then
            (i64.store (global.get $@stack) (i64.const 1745))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store (global.get $@stack) (i64.const 213))
            (global.set $@stack (i32.sub (global.get $@stack) (i32.const 8)))
            (call $printf (global.get $@stack) (i32.const 2))
            (unreachable)))
        (set_local $j (i32.wrap_i64 (i64.ctz (i64.load (get_local $cur)))))
        (if (get_local $verbose)
          (then
            (i64.store (global.get $@stack) (i64.const 1786))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store (global.get $@stack) (i64.extend_i32_s (get_local $j)))
            (global.set $@stack (i32.sub (global.get $@stack) (i32.const 8)))
            (call $printf (global.get $@stack) (i32.const 2))))
        (i64.store (get_local $cur) (i64.xor (i64.load (get_local $cur)) (i64.shl (i64.const 1) (i64.extend_i32_s (get_local $j)))))
        (if (i64.eqz (i64.load (get_local $cur)))
          (then
            (if (get_local $verbose)
              (then
                (i64.store (global.get $@stack) (i64.const 1811))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (i64.store (global.get $@stack) (i64.extend_i32_s (get_local $idx)))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (i64.store (global.get $@stack) (i64.extend_i32_s (get_local $n)))
                (global.set $@stack (i32.sub (global.get $@stack) (i32.const 16)))
                (call $printf (global.get $@stack) (i32.const 3))))
            (i32.store (i32.add (global.get $__mm_avail) (i32.mul (get_local $n) (i32.const 4))) (i32.const -1))))
        (global.set $@stack (get_local $@stack_entry))
        (return (i32.add (i32.add (get_local $cur) (i32.const 8)) (i32.mul (get_local $j) (get_local $a_size))))))
    (unreachable))
  (func $mm_free (param $address i32)
    (local $@stack_entry i32)
    (local $verbose i32)
    (local $unit i32)
    (local $i i32)
    (local $idx i32)
    (local $state i32)
    (local $cur i32)
    (local $n i32)
    (local $a_size i32)
    (local $bits i32)
    (local $j i32)
    (set_local $@stack_entry (global.get $@stack))
    (global.set $__mm_stat_freed (i32.add (global.get $__mm_stat_freed) (i32.const 1)))
    (set_local $unit (i32.add (i32.mul (i32.const 64) (global.get $__mm_min)) (i32.const 12)))
    (set_local $idx (i32.div_s (i32.sub (get_local $address) (global.get $__mm_memory)) (get_local $unit)))
    (set_local $state (i32.load (i32.add (global.get $__mm_memory) (i32.mul (get_local $idx) (get_local $unit)))))
    (if (i32.eq (get_local $state) (i32.const 0))
      (then
        (i64.store (global.get $@stack) (i64.const 1871))
        (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
        (i64.store (global.get $@stack) (i64.const 241))
        (global.set $@stack (i32.sub (global.get $@stack) (i32.const 8)))
        (call $printf (global.get $@stack) (i32.const 2))
        (unreachable)))
    (if (i32.lt_s (get_local $state) (i32.const 0))
      (then
        (if (get_local $verbose)
          (then
            (i64.store (global.get $@stack) (i64.const 1913))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store (global.get $@stack) (i64.extend_i32_s (get_local $idx)))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store (global.get $@stack) (i64.extend_i32_s (i32.sub (i32.const 0) (get_local $state))))
            (global.set $@stack (i32.sub (global.get $@stack) (i32.const 16)))
            (call $printf (global.get $@stack) (i32.const 3))))
        (if (i32.ne (get_local $address) (i32.add (i32.add (global.get $__mm_memory) (i32.mul (get_local $idx) (get_local $unit))) (i32.const 4)))
          (then
            (i64.store (global.get $@stack) (i64.const 1940))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store (global.get $@stack) (i64.const 246))
            (global.set $@stack (i32.sub (global.get $@stack) (i32.const 8)))
            (call $printf (global.get $@stack) (i32.const 2))
            (unreachable)))
        (block $@block_1_break
          (set_local $i (i32.const 0))
          (loop $@block_1_continue
            (br_if $@block_1_break (i32.ge_s (get_local $i) (i32.sub (i32.const 0) (get_local $state))))
            (i32.store (i32.add (global.get $__mm_memory) (i32.mul (i32.add (get_local $idx) (get_local $i)) (get_local $unit))) (i32.const 0))
            (set_local $i (i32.add (get_local $i) (i32.const 1)))
            (br $@block_1_continue))))
      (else
        (set_local $cur (i32.add (i32.add (global.get $__mm_memory) (i32.mul (get_local $idx) (get_local $unit))) (i32.const 4)))
        (set_local $n (i32.sub (get_local $state) (i32.const 1)))
        (if (i32.gt_s (get_local $n) (i32.const 6))
          (then
            (i64.store (global.get $@stack) (i64.const 1394))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store (global.get $@stack) (i64.const 253))
            (global.set $@stack (i32.sub (global.get $@stack) (i32.const 8)))
            (call $printf (global.get $@stack) (i32.const 2))
            (unreachable)))
        (set_local $a_size (global.get $__mm_min))
        (block $@block_2_break
          (set_local $i (i32.const 0))
          (loop $@block_2_continue
            (br_if $@block_2_break (i32.ge_s (get_local $i) (get_local $n)))
            (set_local $a_size (i32.mul (get_local $a_size) (i32.const 2)))
            (set_local $i (i32.add (get_local $i) (i32.const 1)))
            (br $@block_2_continue)))
        (set_local $bits (i32.shl (i32.const 1) (i32.sub (i32.const 6) (get_local $n))))
        (set_local $j (i32.div_s (i32.sub (i32.sub (get_local $address) (get_local $cur)) (i32.const 8)) (get_local $a_size)))
        (if (get_local $verbose)
          (then
            (i64.store (global.get $@stack) (i64.const 2011))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store (global.get $@stack) (i64.extend_i32_s (get_local $idx)))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store (global.get $@stack) (i64.extend_i32_s (get_local $a_size)))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store (global.get $@stack) (i64.extend_i32_s (get_local $n)))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store (global.get $@stack) (i64.extend_i32_s (get_local $j)))
            (global.set $@stack (i32.sub (global.get $@stack) (i32.const 32)))
            (call $printf (global.get $@stack) (i32.const 5))))
        (if (i32.eqz (if (result i32) (i32.lt_s (get_local $j) (i32.const 0)) (then (i32.const 0)) (else (i32.ne (i32.lt_s (get_local $j) (get_local $bits)) (i32.const 0)))))
          (then
            (i64.store (global.get $@stack) (i64.const 2055))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store (global.get $@stack) (i64.const 263))
            (global.set $@stack (i32.sub (global.get $@stack) (i32.const 8)))
            (call $printf (global.get $@stack) (i32.const 2))
            (unreachable)))
        (if (i32.ne (get_local $address) (i32.add (i32.add (get_local $cur) (i32.const 8)) (i32.mul (get_local $j) (get_local $a_size))))
          (then
            (i64.store (global.get $@stack) (i64.const 2105))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store (global.get $@stack) (i64.const 264))
            (global.set $@stack (i32.sub (global.get $@stack) (i32.const 8)))
            (call $printf (global.get $@stack) (i32.const 2))
            (unreachable)))
        (if (i32.wrap_i64 (i64.and (i64.load (get_local $cur)) (i64.shl (i64.const 1) (i64.extend_i32_s (get_local $j)))))
          (then
            (i64.store (global.get $@stack) (i64.const 2176))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store (global.get $@stack) (i64.const 265))
            (global.set $@stack (i32.sub (global.get $@stack) (i32.const 8)))
            (call $printf (global.get $@stack) (i32.const 2))
            (unreachable)))
        (i64.store (get_local $cur) (i64.xor (i64.load (get_local $cur)) (i64.shl (i64.const 1) (i64.extend_i32_s (get_local $j)))))
        (if (i32.lt_s (i32.load (i32.add (global.get $__mm_avail) (i32.mul (get_local $n) (i32.const 4)))) (i32.const 0))
          (then
            (if (get_local $verbose)
              (then
                (i64.store (global.get $@stack) (i64.const 1599))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (i64.store (global.get $@stack) (i64.extend_i32_s (get_local $n)))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (i64.store (global.get $@stack) (i64.extend_i32_s (get_local $idx)))
                (global.set $@stack (i32.sub (global.get $@stack) (i32.const 16)))
                (call $printf (global.get $@stack) (i32.const 3))))
            (i32.store (i32.add (global.get $__mm_avail) (i32.mul (get_local $n) (i32.const 4))) (get_local $idx)))
          (else
            (if (get_local $verbose)
              (then
                (i64.store (global.get $@stack) (i64.const 2258))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (i64.store (global.get $@stack) (i64.extend_i32_s (get_local $n)))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (i64.store (global.get $@stack) (i64.extend_i32_s (i32.load (i32.add (global.get $__mm_avail) (i32.mul (get_local $n) (i32.const 4))))))
                (global.set $@stack (i32.sub (global.get $@stack) (i32.const 16)))
                (call $printf (global.get $@stack) (i32.const 3))))))
        (if (i32.gt_s (i32.const 1) (i32.wrap_i64 (i64.popcnt (i64.load (get_local $cur)))))
          (then
            (i64.store (global.get $@stack) (i64.const 2293))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store (global.get $@stack) (i64.const 277))
            (global.set $@stack (i32.sub (global.get $@stack) (i32.const 8)))
            (call $printf (global.get $@stack) (i32.const 2))
            (unreachable)))
        (if (i32.gt_s (i32.wrap_i64 (i64.popcnt (i64.load (get_local $cur)))) (get_local $bits))
          (then
            (i64.store (global.get $@stack) (i64.const 2355))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store (global.get $@stack) (i64.const 278))
            (global.set $@stack (i32.sub (global.get $@stack) (i32.const 8)))
            (call $printf (global.get $@stack) (i32.const 2))
            (unreachable)))
        (if (if (result i32) (i32.eq (i32.load (i32.add (global.get $__mm_avail) (i32.mul (get_local $n) (i32.const 4)))) (get_local $idx)) (then (i32.const 0)) (else (i32.ne (i32.eq (i32.wrap_i64 (i64.popcnt (i64.load (get_local $cur)))) (get_local $bits)) (i32.const 0))))
          (then
            (if (get_local $verbose)
              (then
                (i64.store (global.get $@stack) (i64.const 2420))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (i64.store (global.get $@stack) (i64.extend_i32_s (get_local $n)))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (i64.store (global.get $@stack) (i64.extend_i32_s (i32.load (i32.add (global.get $__mm_avail) (i32.mul (get_local $n) (i32.const 4))))))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (i64.store (global.get $@stack) (i64.extend_i32_s (get_local $idx)))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (i64.store (global.get $@stack) (i64.load (get_local $cur)))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (i64.store (global.get $@stack) (i64.extend_i32_s (get_local $state)))
                (global.set $@stack (i32.sub (global.get $@stack) (i32.const 40)))
                (call $printf (global.get $@stack) (i32.const 6))))
            (i32.store (i32.add (global.get $__mm_memory) (i32.mul (get_local $idx) (get_local $unit))) (i32.const 0))))))
    (global.set $@stack (get_local $@stack_entry)))
  (func $mm_print_units
    (local $@stack_entry i32)
    (local $unit i32)
    (local $idx i32)
    (local $state i32)
    (set_local $@stack_entry (global.get $@stack))
    (set_local $unit (i32.add (i32.mul (i32.const 64) (global.get $__mm_min)) (i32.const 12)))
    (block $@block_1_break
      (loop $@block_1_continue
        (br_if $@block_1_break (i32.ge_s (get_local $idx) (global.get $__mm_inuse)))
        (set_local $state (i32.load (i32.add (global.get $__mm_memory) (i32.mul (get_local $idx) (get_local $unit)))))
        (if (i32.eqz (get_local $state))
          (then
            (i64.store (global.get $@stack) (i64.const 2503))
            (global.set $@stack (i32.sub (global.get $@stack) (i32.const 0)))
            (call $printf (global.get $@stack) (i32.const 1)))
          (else
            (if (i32.lt_s (get_local $state) (i32.const 0))
              (then
                (i64.store (global.get $@stack) (i64.const 2505))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (i64.store (global.get $@stack) (i64.extend_i32_s (i32.sub (i32.const 0) (get_local $state))))
                (global.set $@stack (i32.sub (global.get $@stack) (i32.const 8)))
                (call $printf (global.get $@stack) (i32.const 2))
                (set_local $idx (i32.add (get_local $idx) (i32.sub (i32.sub (i32.const 0) (get_local $state)) (i32.const 1)))))
              (else
                (i64.store (global.get $@stack) (i64.const 2512))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (i64.store (global.get $@stack) (i64.extend_i32_s (i32.sub (get_local $state) (i32.const 1))))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (i64.store (global.get $@stack) (i64.extend_i32_s (i32.wrap_i64 (i64.popcnt (i64.load (i32.add (i32.add (global.get $__mm_memory) (i32.mul (get_local $idx) (get_local $unit))) (i32.const 4)))))))
                (global.set $@stack (i32.sub (global.get $@stack) (i32.const 16)))
                (call $printf (global.get $@stack) (i32.const 3))))))
        (set_local $idx (i32.add (get_local $idx) (i32.const 1)))
        (br $@block_1_continue)))
    (i64.store (global.get $@stack) (i64.const 2526))
    (global.set $@stack (i32.sub (global.get $@stack) (i32.const 0)))
    (call $printf (global.get $@stack) (i32.const 1))
    (global.set $@stack (get_local $@stack_entry)))
  (func $mulberry32 (result f64)
    (local $t i32)
    (global.set $seed (i32.add (global.get $seed) (i32.const 1831565813)))
    (set_local $t (global.get $seed))
    (set_local $t (i32.mul (i32.xor (get_local $t) (i32.shr_u (get_local $t) (i32.const 15))) (i32.or (get_local $t) (i32.const 1))))
    (set_local $t (i32.xor (get_local $t) (i32.add (get_local $t) (i32.mul (i32.xor (get_local $t) (i32.shr_u (get_local $t) (i32.const 7))) (i32.or (get_local $t) (i32.const 61))))))
    (f64.div (f64.convert_i32_u (i32.xor (get_local $t) (i32.shr_u (get_local $t) (i32.const 14)))) (f64.const 4.294967296E9)))
  (func $allocate (param $id i32) (result i32)
    (local $unit i32)
    (set_local $unit (call $mm_malloc (i32.const 108)))
    (memory.fill (get_local $unit) (i32.const 0) (i32.const 108))
    (i32.store (get_local $unit) (get_local $id))
    (i32.store (i32.add (get_local $unit) (i32.const 4)) (i32.xor (get_local $id) (i32.const 816191)))
    (get_local $unit))
  (func $verify (param $unit i32)
    (local $@stack_entry i32)
    (set_local $@stack_entry (global.get $@stack))
    (if (i32.ne (i32.load (i32.add (get_local $unit) (i32.const 4))) (i32.xor (i32.load (get_local $unit)) (i32.const 816191)))
      (then
        (i64.store (global.get $@stack) (i64.const 2528))
        (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
        (i64.store (global.get $@stack) (i64.const 337))
        (global.set $@stack (i32.sub (global.get $@stack) (i32.const 8)))
        (call $printf (global.get $@stack) (i32.const 2))
        (unreachable)))
    (global.set $@stack (get_local $@stack_entry)))
  (func $main (export "main") (result i32)
    (local $@stack_entry i32)
    (local $n_iter i32)
    (local $iter i32)
    (local $idx i32)
    (set_local $@stack_entry (global.get $@stack))
    (global.set $storage (call $mm_malloc (i32.const 8000)))
    (memory.fill (global.get $storage) (i32.const 0) (i32.const 4000))
    (set_local $n_iter (i32.const 100000))
    (i64.store (global.get $@stack) (i64.const 2598))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (i64.store (global.get $@stack) (i64.const 1000))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (i64.store (global.get $@stack) (i64.extend_i32_s (get_local $n_iter)))
    (global.set $@stack (i32.sub (global.get $@stack) (i32.const 16)))
    (call $printf (global.get $@stack) (i32.const 3))
    (block $@block_1_break
      (loop $@block_1_continue
        (br_if $@block_1_break (i32.ge_s (get_local $iter) (get_local $n_iter)))
        (set_local $idx (i32.trunc_f64_s (f64.mul (call $mulberry32) (f64.const 1000.0))))
        (if (i32.load (i32.add (global.get $storage) (i32.mul (get_local $idx) (i32.const 4))))
          (then
            (call $verify (i32.load (i32.add (global.get $storage) (i32.mul (get_local $idx) (i32.const 4)))))
            (call $mm_free (i32.load (i32.add (global.get $storage) (i32.mul (get_local $idx) (i32.const 4)))))
            (i32.store (i32.add (global.get $storage) (i32.mul (get_local $idx) (i32.const 4))) (i32.const 0)))
          (else
            (i32.store (i32.add (global.get $storage) (i32.mul (get_local $idx) (i32.const 4))) (call $allocate (i32.add (i32.const 1) (get_local $iter))))))
        (set_local $iter (i32.add (get_local $iter) (i32.const 1)))
        (br $@block_1_continue)))
    (call $mm_print_units)
    (call $mm_free (global.get $storage))
    (i64.store (global.get $@stack) (i64.const 2668))
    (global.set $@stack (i32.sub (global.get $@stack) (i32.const 0)))
    (call $printf (global.get $@stack) (i32.const 1))
    (global.set $@stack (get_local $@stack_entry))
    (i32.const 0)))
