#! /usr/bin/env node
'use strict';

const fs = require('fs');
const {wasm_printf} = require('./wasm-printf');

const wasm_bytes = new Uint8Array(fs.readFileSync(process.argv[2]));
let wasm_mem;

WebAssembly.instantiate(wasm_bytes, {c4wa: {
    printf: wasm_printf(() => new Uint8Array(wasm_mem.buffer),
        x => process.stdout.write(x))}})
    .then(wasm => {
        wasm_mem = wasm.instance.exports.memory;
        wasm.instance.exports.main()
    });